export const courseData = [
  {
    id: 1,
    name: "Angular Crash Course",
    price: 163.04,
    instructor: "Gelya Gilley",
    image: "https://i.ibb.co/XzgPCXX/hqdefault.jpg",
  },
  {
    id: 2,
    name: "Vue-Laravel Crud",
    price: 86.32,
    instructor: "Cordey Twelftree",
    image: "https://i.ibb.co/GMw374W/vue-laravel-crud.png",
  },
  {
    id: 3,
    name: "Python Master Course",
    price: 190.97,
    instructor: "Bev Vanezis",
    image: "https://i.ibb.co/NmJbxtm/Udemy-Advance-Python-Learning-Courses.png",
  },
  {
    id: 4,
    name: "Vue-Laravel Crud",
    price: 86.32,
    instructor: "Cordey Twelftree",
    image: "https://i.ibb.co/GMw374W/vue-laravel-crud.png",
  },
  {
    id: 5,
    name: "Flutter N Dart Development",
    price: 157.57,
    instructor: "Merlina Mullender",
    image: "https://i.ibb.co/hMS2N6g/download.png",
  },
  {
    id: 6,
    name: "PHP : Web Development Fundamentals",
    price: 143.25,
    instructor: "Ricoriki McGaugey",
    image: "https://i.ibb.co/grqw5sH/2488654-e156-3.jpg",
  },
  {
    id: 7,
    name: "Web Dev v3 with React",
    price: 130.13,
    instructor: "Bethena Pelman",
    image:
      "https://i.ibb.co/5FtRRHY/116096125-10157333578881891-5073228303715095638-o.jpg",
  },
  {
    id: 8,
    name: "PHP Complete Crash Course",
    price: 136.48,
    instructor: "Woodie Henden",
    image: "https://i.ibb.co/y4Pg8jp/2417586-15ae.jpg",
  },

  {
    id: 9,
    name: "React-Redux Complete Guide",
    price: 196.24,
    instructor: "Cobbie Perkins",
    image: "https://i.ibb.co/1LFN384/guide-for-react-redux.jpg",
  },
  {
    id: 10,
    name: "Complete Web Development with Jhankar Mahbub",
    price: 59.51,
    instructor: "Jhankar Mahbub",
    image: "https://i.ibb.co/mC0nVFX/13a638d18be03e3123b1af8e74610680.jpg",
  },
  {
    id: 11,
    name: "Angular Crash Course",
    price: 163.04,
    instructor: "Gelya Gilley",
    image: "https://i.ibb.co/XzgPCXX/hqdefault.jpg",
  },
  {
    id: 12,
    name: "Django : The Complete Guide",
    price: 33.86,
    instructor: "Jaime Hambleton",
    image: "https://i.ibb.co/3hGy0ZR/images.png",
  },
  {
    id: 13,
    name: "Complete Web Development 2.0",
    price: 23.89,
    instructor: "Sadye Olerenshaw",
    image: "https://i.ibb.co/VJBmLXS/625204-436a-2.jpg",
  },

  {
    id: 14,
    name: "Ruby on Rails Crash Course",
    price: 83.53,
    instructor: "Johanna Krzyzaniak",
    image: "https://i.ibb.co/kM4bn03/maxresdefault-1.jpg",
  },
  {
    id: 15,
    name: "Go Lang : Crash Course",
    price: 29.58,
    instructor: "Andee Wandrack",
    image: "https://i.ibb.co/MSSGGph/maxresdefault.jpg",
  },
  {
    id: 16,
    name: "Be a Master in GO Lang",
    price: 42.22,
    instructor: "Paulette Waterhouse",
    image: "https://i.ibb.co/9rWC1SP/Master-Go-Course-Badge-Dark-HD.png",
  },
];
